FROM node:24.15-slim AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci --include=optional

COPY . .

RUN npm run build



FROM nginx:alpine

COPY --from=builder ./app/dist /usr/share/nginx/html

EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]


