run-name: Orchestrate CI workflow
name: Orchestrate CI workflow

on:
    push:
        branches: [master]
    workflow_dispatch:

jobs:
    changes:
        name: Findout which files has changed
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code from GitHub to runner machine
              uses: actions/checkout@v6
              with:
                  fetch-depth: 0
            - name: Filter the services that has code changes
              uses: dorny/paths-filter@v4
              with:
                  filters: |
                      config-server:
                          - 'precisionstore/config-server/**'
                      eureka-server:
                          - 'precisionstore/eureka-server/**'
                      api-gateway:
                          - 'precisionstore/api-gateway/**'
                      user-service:
                          - 'precisionstore/user-service/**'
                      product-service:
                          - 'precisionstore/product-service/**'
                      order-service:
                          - 'precisionstore/order-service/**'
                      cart-service:
                          - 'precisionstore/cart-service/**'
        outputs:
            config-server:
            eureka-server:
            api-gateway:
            user-service:
            product-service:
            order-service:
            cart-service:

    orchestrate:
        needs: changes

        strategy:
            matrix:
                service: 
                    - config-server
                    - eureka-server
                    - api-gateway
                    - cart-service
                    - order-service
                    - user-service
                    - product-service
            fail-fast: false
        if: ${{ needs.changes.outputs[matrix.service] == 'true' }}
        name: Build ${{ matrix.service }} service
        uses: ./.github/workflows/ci.yaml
        with:
            service-name: ${{ matrix.service }}
            service-directory: precisionstore/${{ matrix.service }}
        
        
                
